"""add table stock

Revision ID: 17d352d3850f
Revises: 2685da3770bd
Create Date: 2023-12-25 15:01:30.810646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d352d3850f'
down_revision: Union[str, None] = '2685da3770bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('symbol'),
    schema='public'
    )
    op.create_index(op.f('ix_public_stock_name'), 'stock', ['name'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_stock_name'), table_name='stock', schema='public')
    op.drop_table('stock', schema='public')
    # ### end Alembic commands ###
