"""add column verify_code to user

Revision ID: 2685da3770bd
Revises: 99bf025c0ebb
Create Date: 2023-12-25 15:01:09.197066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2685da3770bd'
down_revision: Union[str, None] = '99bf025c0ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('verify_code', sa.String(), nullable=True), schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verify_code', schema='auth')
    # ### end Alembic commands ###
