"""add stocks gold_list

Revision ID: 7cda2a48d41f
Revises: f7757918744c
Create Date: 2024-01-03 23:47:56.857373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cda2a48d41f'
down_revision: Union[str, None] = 'f7757918744c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gold_list',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('symbol'),
    schema='public'
    )
    op.create_index(op.f('ix_public_gold_list_create_time'), 'gold_list', ['create_time'], unique=False, schema='public')
    op.create_table('stocks',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True, comment='最新价'),
    sa.Column('change_percent', sa.Float(), nullable=True, comment='涨跌幅'),
    sa.Column('change', sa.Float(), nullable=True, comment='涨跌额'),
    sa.Column('volume', sa.Float(), nullable=True, comment='成交量'),
    sa.Column('amount', sa.Float(), nullable=True, comment='成交额'),
    sa.Column('amplitude', sa.Float(), nullable=True, comment='振幅'),
    sa.Column('high', sa.Float(), nullable=True, comment='最高'),
    sa.Column('low', sa.Float(), nullable=True, comment='最低'),
    sa.Column('open', sa.Float(), nullable=True, comment='今开'),
    sa.Column('previous_close', sa.Float(), nullable=True, comment='昨收'),
    sa.Column('volume_rate', sa.Float(), nullable=True, comment='量比'),
    sa.Column('turnover_rate', sa.Float(), nullable=True, comment='换手率'),
    sa.Column('pe', sa.Float(), nullable=True, comment='市盈率-动态'),
    sa.Column('pb', sa.Float(), nullable=True, comment='市净率'),
    sa.Column('market_value', sa.Float(), nullable=True, comment='总市值'),
    sa.Column('circulat_value', sa.Float(), nullable=True, comment='流通市值'),
    sa.Column('growth_rate', sa.Float(), nullable=True, comment='涨速'),
    sa.Column('minute_5_growth', sa.Float(), nullable=True, comment='5分钟涨跌'),
    sa.Column('day_60_growth', sa.Float(), nullable=True, comment='60日涨跌幅'),
    sa.Column('this_year_growth', sa.Float(), nullable=True, comment='年初至今涨跌幅'),
    sa.PrimaryKeyConstraint('symbol'),
    schema='public'
    )
    op.create_index(op.f('ix_public_stocks_exchange'), 'stocks', ['exchange'], unique=False, schema='public')
    op.create_index(op.f('ix_public_stocks_name'), 'stocks', ['name'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_stocks_name'), table_name='stocks', schema='public')
    op.drop_index(op.f('ix_public_stocks_exchange'), table_name='stocks', schema='public')
    op.drop_table('stocks', schema='public')
    op.drop_index(op.f('ix_public_gold_list_create_time'), table_name='gold_list', schema='public')
    op.drop_table('gold_list', schema='public')
    # ### end Alembic commands ###
