"""add table profile

Revision ID: 8a259301c796
Revises: 17d352d3850f
Create Date: 2023-12-25 15:10:28.655661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a259301c796'
down_revision: Union[str, None] = '17d352d3850f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['auth.user.email'], ),
    sa.PrimaryKeyConstraint('email'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile', schema='public')
    # ### end Alembic commands ###
