"""add stocks table

Revision ID: ebd4898b0010
Revises: f7757918744c
Create Date: 2024-01-02 17:33:54.119421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebd4898b0010'
down_revision: Union[str, None] = 'f7757918744c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('symbol'),
    schema='public'
    )
    op.create_index(op.f('ix_public_stocks_exchange'), 'stocks', ['exchange'], unique=False, schema='public')
    op.create_index(op.f('ix_public_stocks_name'), 'stocks', ['name'], unique=False, schema='public')
    op.drop_constraint('profiles_email_fkey', 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'users', ['email'], ['email'], source_schema='public', referent_schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', schema='public', type_='foreignkey')
    op.create_foreign_key('profiles_email_fkey', 'profiles', 'users', ['email'], ['email'], referent_schema='auth')
    op.drop_index(op.f('ix_public_stocks_name'), table_name='stocks', schema='public')
    op.drop_index(op.f('ix_public_stocks_exchange'), table_name='stocks', schema='public')
    op.drop_table('stocks', schema='public')
    # ### end Alembic commands ###
